#!/bin/bash -x
for i in 100 200
do
    ./jacobi_serial $i 1000 >> timings/jstiming.txt
done

for i in 100 200
do
    for j in 1 2 3 4
    do
	./jacobi_parallel $i $j 1000 >> timings/jptiming.txt
    done
done


for i in 100 200
do
    ./gauss_serial $i 1000 >> timings/gstiming.txt
done

for i in 100 200
do
    for j in 1 2 3 4
    do
	./gauss_parallel $i $j 1000 >> timings/gptiming.txt
    done
done

for i in 12 24
do
    ./multigrid_serial $i 1000 >> timings/mjs.txt
done

for i in 12 24
do
    for j in 1 2 3 4
    do
	./multigrid_parallel $i $j 1000 >> timings/mjp.txt
    done
done

for i in 12 24
do
    ./multigrid_gauss_serial $i 1000 >> timings/mgs.txt
done

for i in 12 24
do
    for j in 1 2 3 4
    do
	./multigrid_gauss_parallel $i $j 1000 >> timings/mgp.txt
    done
done

for i in 49 99
do
    ./multigrid_serial $i 1000 >> timings/mjs.txt
done

for i in 49 99
do
    for j in 1 2 3 4
    do
	./multigrid_parallel $i $j 1000 >> timings/mjp.txt
    done
done

for i in 49 99
do
    ./multigrid_gauss_serial $i 1000 >> timings/mgs.txt
done

for i in 49 99
do
    for j in 1 2 3 4
    do
	./multigrid_gauss_parallel $i $j 1000 >> timings/mgp.txt
    done
done

exit 0
